import type { Metadata } from "next";
import { AppLegalPage, AppPageLinks, LegalSection, persianSwipeApp } from "../../../components/AppLegalPage";
export const metadata: Metadata = {title: "Persian Swipe Support", description: "Enable Persian Swipe, learn how corrections work, and get help with local Persian typing.", alternates: {canonical: "/apps/persian-swipe/support/"}};
export default function Page() { return <AppLegalPage app={persianSwipeApp} eyebrow="Persian Swipe" title="Support" lede="Enable Persian Swipe, learn how corrections work, and get help with local Persian typing." updated="September 12, 2026" sections={[{"id": "enable", "label": "Enable the keyboard"}, {"id": "swipe", "label": "Swipe and edit"}, {"id": "corrections", "label": "Teach a correction"}, {"id": "troubleshooting", "label": "When learning or prediction differs"}, {"id": "purchase", "label": "Purchase help"}, {"id": "contact", "label": "Contact support"}]}>
<LegalSection id="enable" title="Enable the keyboard"><p>{"Install Persian Swipe, then open Settings → General → Keyboard → Keyboards → Add New Keyboard → Persian Swipe. In a text field, hold the globe and choose Persian Swipe. Full Access is not required. The host app includes a practice keyboard that works before you enable the extension."}</p></LegalSection>
<LegalSection id="swipe" title="Swipe and edit"><p>{"Slide through the letters of a Persian word and lift to insert it. Tap a candidate to choose another spelling. Tap letters for words you prefer to type manually. Hold ا for آ and other forms; ی, و, and ه also have alternatives. The compact half-space key inserts نیم‌فاصله. Hold Backspace to repeat deletion."}</p></LegalSection>
<LegalSection id="corrections" title="Teach a correction"><p>{"Swipe, delete or edit the wrong word, tap the intended word, then press Space or Return. The message اصلاح یاد گرفته شد confirms that the correction was recorded. One explicit correction can teach similar future swipe paths. Finish the correction within 60 seconds, in the same text field and at the same position. Deleting alone teaches nothing; backspacing immediately after confirmation undoes the lesson. Ordinary new words require two completed typed uses. Practice and the installed keyboard learn separately."}</p></LegalSection>
<LegalSection id="troubleshooting" title="When learning or prediction differs"><p>{"Check Learn my words in the gear menu. Changing fields, moving the cursor, switching keyboards, deleting preceding text, or unavailable text context can cancel pending correction learning. Swipe accuracy varies with words and gestures; use the candidate bar or tap typing when needed. Some apps and secure fields do not allow custom keyboards. If storage reports an error, save any needed text and use the confirmed Clear learned words action to start a fresh dictionary."}</p></LegalSection>
<LegalSection id="purchase" title="Purchase help"><p>{"Persian Swipe is a one-time paid App Store download with no subscription or in-app purchases. The current price and regional currency are displayed by Apple before purchase. Reinstall using the Apple Account that purchased it; billing and refund requests are handled by Apple."}</p></LegalSection>
<LegalSection id="contact" title="Contact support"><p>{"Email mehrdadz@neuralint.io with the app version, iOS version, device model, and a short description of the issue. You may provide a non-sensitive example word and expected result. Do not include passwords, private messages, or your personal dictionary."}</p></LegalSection>
<AppPageLinks app={persianSwipeApp} />
</AppLegalPage>; }
