import type { Metadata } from "next";
import { AppLegalPage, AppPageLinks, LegalSection, persianSwipeApp } from "../../../components/AppLegalPage";
export const metadata: Metadata = {title: "Persian Swipe Privacy Policy", description: "Persian Swipe processes typing and learns words locally, without accounts, advertising, tracking, or servers.", alternates: {canonical: "/apps/persian-swipe/privacy/"}};
export default function Page() { return <AppLegalPage app={persianSwipeApp} eyebrow="Persian Swipe" title="Privacy Policy" lede="Persian Swipe processes typing and learns words locally, without accounts, advertising, tracking, or servers." updated="September 12, 2026" sections={[{"id": "local", "label": "Recognition stays on your device"}, {"id": "learning", "label": "What personalization stores"}, {"id": "controls", "label": "Your controls"}, {"id": "context", "label": "Text context and other apps"}, {"id": "purchase", "label": "Purchases and support"}, {"id": "contact", "label": "Questions and changes"}]}>
<LegalSection id="local" title="Recognition stays on your device"><p>{"Persian Swipe performs swipe recognition, candidate ranking, and personalization entirely on your device. The keyboard and host app make no network requests and have no analytics or advertising SDK. We do not collect your typing, messages, or swipe patterns. Full Access is not required."}</p></LegalSection>
<LegalSection id="learning" title="What personalization stores"><p>{"Learning starts enabled. The keyboard stores up to 2,000 normalized Persian words with usage counts, confirmed-choice counts, and last-used dates. Explicit corrections may store the mistaken and intended words, a compact 16-point normalized swipe pattern without touch timestamps, and a correction date. At most 128 correction examples are kept; examples older than 90 days stop influencing prediction. Full messages, keystroke histories, and practice drafts are not saved by the app."}</p></LegalSection>
<LegalSection id="controls" title="Your controls"><p>{"Tap the gear above the keyboard. Turn off Learn my words to stop learning and personalized predictions while retaining saved entries. Clear learned words deletes both word frequencies and swipe correction examples. Practice and the installed keyboard have separate private dictionaries. Data is protected by iOS file protection, excluded from backup, and not synced. Deleting the app removes its local data."}</p></LegalSection>
<LegalSection id="context" title="Text context and other apps"><p>{"iOS supplies limited surrounding text to support prediction and safe replacement. This context is processed temporarily on device and not transmitted to us. The keyboard does not import a host document into its dictionary. iOS uses the system keyboard for secure fields and some phone fields; apps may disable custom keyboards. Text you enter into another app is governed by that app and its privacy policy."}</p></LegalSection>
<LegalSection id="purchase" title="Purchases and support"><p>{"Apple processes App Store purchases under its own policies. If you choose to email support, your email address and the information you send are used to respond to your request, not for advertising. Do not send passwords, sensitive messages, or your personal dictionary. The app does not send automatic diagnostic reports to us."}</p></LegalSection>
<LegalSection id="contact" title="Questions and changes"><p>{"For privacy questions or to request deletion of support correspondence, email mehrdadz@neuralint.io. Material changes to these practices will be reflected in this policy and the App Store disclosures."}</p></LegalSection>
<AppPageLinks app={persianSwipeApp} />
</AppLegalPage>; }
